### ISSUE TITLE
different topic I know but...

### ISSUE THREAD

**Issue by osevan** [useidel/signal-desktop-fedora#1]
Hi Udo,
I want know if tcp stealth in openssh is already mainlined? 

I mean without patch - I guess no. 

And where I can find working patch for newest openssh?

Project website isnt available anymore,nor I can find libnockify, for LD preloading sockoptions.

Thanks and

Best regards

**Comment by useidel** [comment]
Hiya, unfortunately, I cannot help here. I have dropped the topic years ago and lost track of the project. Based on your research I would guess the days for TCP Stealth are over. 
Sorry,
Udo

**Comment by useidel** [comment]
:-(

**Comment by useidel** [comment]
Nothing else to be said from my side
