### ISSUE TITLE
f38 packages are missing

### ISSUE THREAD

**Issue by lnicola** [useidel/signal-desktop-fedora#2]
https://copr.fedorainfracloud.org/coprs/useidel/signal-desktop/package/signal-desktop/

Might be caused by this, but I didn't find any reference to it in the specfile:

> The current build requires internet access and the additional repo https://rpm.nodesource.com/pub_16.x/fc/$releasever/$basearch

**Comment by useidel** [comment]
Yes. There are no f38 packages yet for nodejs available on that external repo. Hence I have not yet enabled f38 build repos. 
I guess we need to wait until f38 is GA.

**Comment by lnicola** [comment]
I expected that. But since this is probably the first time I read a specfile, would you mind explaining how that repo is used? I see `nodejs` in the build dependencies, but there's no version or reference to the repo.

**Comment by useidel** [comment]
Okies. The package manager (actually DNF in that case) will resolve the requirement for nodejs and install the "best" version. For that DNF will search through the configure software repos .. which here includes the external one. 
Having said that, I am right now testing if the Fedora shipped nodejs is good enough now and would work too. If this turns out to be true I can and will enable f38 for the builds.

**Comment by useidel** [comment]
Have done some test builds with the fedora shipped npm and that seems to work. Hence I could remove the dependency on the external repo and consequently, enable f38 builds.

**Comment by useidel** [comment]
See above and latest builds (https://copr.fedorainfracloud.org/coprs/useidel/signal-desktop/build/5742371/) will deliver f38 packages

**Comment by lnicola** [comment]
> he package manager (actually DNF in that case) will resolve the requirement for nodejs and install the "best" version. For that DNF will search through the configure software repos .. which here includes the external one.

Yeah, but the repo isn't in the specfile (https://github.com/useidel/signal-desktop-fedora/commit/898238ff9eb97565aab5f819b0227278365e1be2 doesn't mention it), so I was asking how it was configured. Anyway..

> See above and latest builds

I can confirm that the build from https://copr.fedorainfracloud.org/coprs/useidel/signal-desktop/build/5742371/ works. https://copr.fedorainfracloud.org/coprs/useidel/signal-desktop/package/signal-desktop/ is still empty (maybe you need to promote it manually, no idea).

Just one thing: I'll have to remove `--use-tray-icon` from the `.desktop` file, since that's not working in GNOME.

Thanks for looking into this!

**Comment by useidel** [comment]
Regarding the repo and mentioning in the SPEC file. It is new to me that particular software repos are mentioned in the RPM SPEC file. One does mention dependencies and then it is up to the build system to satisfy these dependencies. A way to "mention" that would be comments. Having said that: my experience is that a clear definition of the build platform is more important than the actual SPEC file. Hence, I have mentioned the need for the external repo there. And to be fair. I have outlined that external repo also in the Readme of the github repo hosting the SPEC file.
Regarding the COPR repo. Please do wait a few days. We are just in front of an schedule outage of the platform. So some things will not work at the moment as expected as preparation for that. 
Lastly, I will have a look into the GNOME problem you have mentioned in the .desktop file.

**Comment by lnicola** [comment]
> It is new to me that particular software repos are mentioned in the RPM SPEC file.

I don't know that either, it was just a guess -- COPR can't know all the repositories in the world, and if I get the SRPM and build it locally, my system surely won't. If you didn't configure it somewhere else, I expect it wasn't actually used. COPR can't read the README, right? :-).

> Regarding the COPR repo. Please do wait a few days. We are just in front of an schedule outage of the platform.

The page is already showing one x64 package (EDIT: one package download), but it doesn't appear in the list. Maybe it just takes a bit to build, I have no experience with this.

> Lastly, I will have a look into the GNOME problem you have mentioned in the .desktop file.

Don't worry about it. It's intentional (for KDE), but GNOME needs an extension to show those icons. I don't think you can make do much about it.

**Comment by useidel** [comment]
Looks like you need to make yourself a bit more familiar how COPR works, e.g. how to configure additonal repos and how packages are published.
